spring:
  application:
    name: ticket-service
  jpa:
    hibernate:
      ddl-auto: create-drop

redis:
  timeout: 3s
  lock:
    wait-time: 5s
    lease-time: 3s

queue:
  max-processing-count: 100
  entry-timeout: 5m
  waiting-timeout: 30m
  sse-timeout: 10m

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

ticket:
  lock:
    strategy: pessimistic
