server:
  tomcat:
    accept-count: 100
    threads:
      max: 200
      min-spare: 50

spring:
  application:
    name: ticket-service
  jpa:
    hibernate:
      ddl-auto: create-drop

redis:
  timeout: 3s
  lock:
    wait-time: 5s
    lease-time: 3s

queue:
  max-processing-count: 200
  max-waiting-count: 20000
  entry-timeout: 5m
  waiting-timeout: 30m
  sse-timeout: 10m
  position-broadcast-interval: 5s

sse:
  thread-pool:
    core-size: 10
    max-size: 50
    queue-capacity: 100
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

ticket:
  lock:
    strategy: pessimistic
